#ifndef JERKMINIMIZATIONTESTOPENLOOP__VISIBILITY_CONTROL_H_
#define JERKMINIMIZATIONTESTOPENLOOP__VISIBILITY_CONTROL_H_
#if defined _WIN32 || defined __CYGWIN__
  #ifdef __GNUC__
    #define JERKMINIMIZATIONTESTOPENLOOP_EXPORT __attribute__ ((dllexport))
    #define JERKMINIMIZATIONTESTOPENLOOP_IMPORT __attribute__ ((dllimport))
  #else
    #define JERKMINIMIZATIONTESTOPENLOOP_EXPORT __declspec(dllexport)
    #define JERKMINIMIZATIONTESTOPENLOOP_IMPORT __declspec(dllimport)
  #endif
  #ifdef JERKMINIMIZATIONTESTOPENLOOP_BUILDING_LIBRARY
    #define JERKMINIMIZATIONTESTOPENLOOP_PUBLIC JERKMINIMIZATIONTESTOPENLOOP_EXPORT
  #else
    #define JERKMINIMIZATIONTESTOPENLOOP_PUBLIC JERKMINIMIZATIONTESTOPENLOOP_IMPORT
  #endif
  #define JERKMINIMIZATIONTESTOPENLOOP_PUBLIC_TYPE JERKMINIMIZATIONTESTOPENLOOP_PUBLIC
  #define JERKMINIMIZATIONTESTOPENLOOP_LOCAL
#else
  #define JERKMINIMIZATIONTESTOPENLOOP_EXPORT __attribute__ ((visibility("default")))
  #define JERKMINIMIZATIONTESTOPENLOOP_IMPORT
  #if __GNUC__ >= 4
    #define JERKMINIMIZATIONTESTOPENLOOP_PUBLIC __attribute__ ((visibility("default")))
    #define JERKMINIMIZATIONTESTOPENLOOP_LOCAL  __attribute__ ((visibility("hidden")))
  #else
    #define JERKMINIMIZATIONTESTOPENLOOP_PUBLIC
    #define JERKMINIMIZATIONTESTOPENLOOP_LOCAL
  #endif
  #define JERKMINIMIZATIONTESTOPENLOOP_PUBLIC_TYPE
#endif
#endif  // JERKMINIMIZATIONTESTOPENLOOP__VISIBILITY_CONTROL_H_
// Generated 16-Nov-2023 10:49:28
// Copyright 2019-2020 The MathWorks, Inc.
